language: node_js
node_js:
   - "4"
   - "6"
   - "7"
os:
  - linux
sudo: required
before_install:
  - npm install -g yarn --cache-min 999999999
  - sudo apt-get -qq update
  - sudo apt-get install build-essential autoconf libtool g++
services:
  - mysql
  - mongodb
