language: node_js
node_js:
   - "4"
   - "6"
   - "7"
os:
  - linux
sudo: required
before_install:
  - npm install -g yarn --cache-min 999999999
services:
  - mysql
  - mongodb
  - redis
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
